Added error handling after bundle install

diff --git a/rails_new_app b/rails_new_app
--- a/rails_new_app
+++ b/rails_new_app
@@ -41,7 +41,12 @@ echo ' done!'
 # Install rails in the application directory
 echo -n 'Running bundle install...'
 bundle install --path vendor/bundle >/dev/null
-echo ' done!'
+if [ $? -eq 0 ]; then
+  echo ' done!'
+else
+  echo ' fail!'
+  exit 1
+fi
 
 # Generate a new rails application
 echo 'Creating new rails application'
